/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_add (void);
GtkWidget* create_window_mod (void);
GtkWidget* create_window_aff (void);
GtkWidget* create_window_rech (void);
GtkWidget* create_windowlisteparking (void);
GtkWidget* create_window1 (void);
