/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *entry_nom;
  GtkWidget *entry_cin;
  GtkWidget *entry_prenom;
  GtkWidget *entry_telephone;
  GtkObject *jr_adj;
  GtkWidget *jr;
  GtkObject *m_adj;
  GtkWidget *m;
  GtkObject *an_adj;
  GtkWidget *an;
  GtkObject *jr1_adj;
  GtkWidget *jr1;
  GtkObject *m1_adj;
  GtkWidget *m1;
  GtkObject *an1_adj;
  GtkWidget *an1;
  GtkWidget *entry_mail;
  GtkWidget *label6;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *nom;
  GtkWidget *cin;
  GtkWidget *dn;
  GtkWidget *db;
  GtkWidget *region;
  GtkWidget *role;
  GtkWidget *prenom;
  GtkWidget *telephone;
  GtkWidget *inactif;
  GSList *inactif_group = NULL;
  GtkWidget *mail;
  GtkWidget *ville;
  GtkWidget *parking;
  GtkWidget *buttonajout;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label59;
  GtkWidget *button_aff;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label68;
  GtkWidget *label55;
  GtkWidget *actif;
  GSList *actif_group = NULL;
  GtkWidget *staut;
  GtkWidget *entry_role;
  GtkWidget *entry_ville;
  GtkWidget *entry_parking;
  GtkWidget *entry_region;
  GtkWidget *Ajout;
  GtkWidget *fixed2;
  GtkWidget *treeview_agents;
  GtkWidget *entry_cin_cher;
  GtkWidget *label25;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label23;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label26;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label24;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label27;
  GtkWidget *label74;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label28;
  GtkWidget *button_chercher_aff;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label22;
  GtkWidget *label29;
  GtkWidget *c;
  GtkWidget *fixed3;
  GtkWidget *label30;
  GtkWidget *entry_cin_cher2;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label34;
  GtkWidget *label31;
  GtkWidget *button_cher2;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label33;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label32;
  GtkWidget *rs;
  GtkWidget *check;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label70;
  GtkWidget *supppression;
  GtkWidget *fixed4;
  GtkWidget *entry_cin1_modif;
  GtkWidget *label58;
  GtkWidget *buttonchercher;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label62;
  GtkWidget *cin1_modif;
  GtkWidget *buttonenregistrer;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label61;
  GtkWidget *fixed5;
  GtkWidget *entry__nom_modif;
  GtkWidget *entry_prenom_modif;
  GtkWidget *entry_telephone_modif;
  GtkObject *jr_modif_adj;
  GtkWidget *jr_modif;
  GtkObject *m_modif_adj;
  GtkWidget *m_modif;
  GtkObject *an_modif_adj;
  GtkWidget *an_modif;
  GtkObject *jr1_modif_adj;
  GtkWidget *jr1_modif;
  GtkObject *m1_modif_adj;
  GtkWidget *m1_modif;
  GtkObject *an1_modif_adj;
  GtkWidget *an1_modif;
  GtkWidget *entry_mail_modif;
  GtkWidget *button13;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label42;
  GtkWidget *entry_cin_modif;
  GtkWidget *label49;
  GtkWidget *dn_modif;
  GtkWidget *db_modif;
  GtkWidget *region_modif;
  GtkWidget *role_modif;
  GtkWidget *entry_region_modif;
  GtkWidget *entry_role_modif;
  GtkWidget *actif_modif;
  GSList *actif_modif_group = NULL;
  GtkWidget *inactif_modif;
  GSList *inactif_modif_group = NULL;
  GtkWidget *ville_modif;
  GtkWidget *mail_modif;
  GtkWidget *entry_ville_modif;
  GtkWidget *entrty_parking_modif;
  GtkWidget *nom_modif;
  GtkWidget *cin_modif;
  GtkWidget *prenom_modif;
  GtkWidget *statut_modif;
  GtkWidget *telephone_modif;
  GtkWidget *error_modif;
  GtkWidget *label73;
  GtkWidget *modification;
  GtkWidget *fixed6;
  GtkWidget *label64;
  GtkWidget *treeview_reservations;
  GtkWidget *button14;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label65;
  GtkWidget *button15;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label67;
  GtkWidget *label71;
  GtkObject *jr_res_adj;
  GtkWidget *jr_res;
  GtkObject *m_res_adj;
  GtkWidget *m_res;
  GtkObject *an_res_adj;
  GtkWidget *an_res;
  GtkWidget *label72;
  GtkWidget *button_aff_res;
  GtkWidget *label63;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Gestion des Agents"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom, 72, 40);
  gtk_widget_set_size_request (entry_nom, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_cin = gtk_entry_new ();
  gtk_widget_show (entry_cin);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_cin, 72, 80);
  gtk_widget_set_size_request (entry_cin, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_prenom, 360, 40);
  gtk_widget_set_size_request (entry_prenom, 176, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  entry_telephone = gtk_entry_new ();
  gtk_widget_show (entry_telephone);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_telephone, 360, 72);
  gtk_widget_set_size_request (entry_telephone, 176, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_telephone), 8226);

  jr_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  jr = gtk_spin_button_new (GTK_ADJUSTMENT (jr_adj), 1, 0);
  gtk_widget_show (jr);
  gtk_fixed_put (GTK_FIXED (fixed1), jr, 72, 120);
  gtk_widget_set_size_request (jr, 48, 24);

  m_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  m = gtk_spin_button_new (GTK_ADJUSTMENT (m_adj), 1, 0);
  gtk_widget_show (m);
  gtk_fixed_put (GTK_FIXED (fixed1), m, 136, 120);
  gtk_widget_set_size_request (m, 48, 24);

  an_adj = gtk_adjustment_new (1901, 1900, 2020, 1, 10, 10);
  an = gtk_spin_button_new (GTK_ADJUSTMENT (an_adj), 1, 0);
  gtk_widget_show (an);
  gtk_fixed_put (GTK_FIXED (fixed1), an, 192, 120);
  gtk_widget_set_size_request (an, 64, 27);

  jr1_adj = gtk_adjustment_new (7, 1, 31, 1, 10, 10);
  jr1 = gtk_spin_button_new (GTK_ADJUSTMENT (jr1_adj), 1, 0);
  gtk_widget_show (jr1);
  gtk_fixed_put (GTK_FIXED (fixed1), jr1, 80, 160);
  gtk_widget_set_size_request (jr1, 48, 24);

  m1_adj = gtk_adjustment_new (11, 1, 12, 1, 10, 10);
  m1 = gtk_spin_button_new (GTK_ADJUSTMENT (m1_adj), 1, 0);
  gtk_widget_show (m1);
  gtk_fixed_put (GTK_FIXED (fixed1), m1, 136, 160);
  gtk_widget_set_size_request (m1, 48, 24);

  an1_adj = gtk_adjustment_new (2024, 2024, 2200, 1, 10, 10);
  an1 = gtk_spin_button_new (GTK_ADJUSTMENT (an1_adj), 1, 0);
  gtk_widget_show (an1);
  gtk_fixed_put (GTK_FIXED (fixed1), an1, 192, 160);
  gtk_widget_set_size_request (an1, 64, 27);

  entry_mail = gtk_entry_new ();
  gtk_widget_show (entry_mail);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_mail, 360, 144);
  gtk_widget_set_size_request (entry_mail, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mail), 8226);

  label6 = gtk_label_new (_("<span foreground=\"#1a3a6e\">****Bienvenue dans l'espace d'agent****</span>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 160, 8);
  gtk_widget_set_size_request (label6, 276, 17);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 8, 280);
  gtk_widget_set_size_request (button1, 74, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  nom = gtk_label_new (_("Nom"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 16, 48);
  gtk_widget_set_size_request (nom, 57, 17);

  cin = gtk_label_new (_("cin"));
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed1), cin, 16, 88);
  gtk_widget_set_size_request (cin, 57, 17);

  dn = gtk_label_new (_("date\nnaissance"));
  gtk_widget_show (dn);
  gtk_fixed_put (GTK_FIXED (fixed1), dn, 0, 112);
  gtk_widget_set_size_request (dn, 72, 40);

  db = gtk_label_new (_("date d\303\251but\n d'emploi"));
  gtk_widget_show (db);
  gtk_fixed_put (GTK_FIXED (fixed1), db, 0, 144);
  gtk_widget_set_size_request (db, 73, 52);

  region = gtk_label_new (_("R\303\251gion"));
  gtk_widget_show (region);
  gtk_fixed_put (GTK_FIXED (fixed1), region, 8, 208);
  gtk_widget_set_size_request (region, 57, 17);

  role = gtk_label_new (_("Role"));
  gtk_widget_show (role);
  gtk_fixed_put (GTK_FIXED (fixed1), role, 16, 248);
  gtk_widget_set_size_request (role, 57, 17);

  prenom = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), prenom, 272, 40);
  gtk_widget_set_size_request (prenom, 57, 17);

  telephone = gtk_label_new (_("num\303\251ro de\n telephone"));
  gtk_widget_show (telephone);
  gtk_fixed_put (GTK_FIXED (fixed1), telephone, 272, 64);
  gtk_widget_set_size_request (telephone, 80, 48);

  inactif = gtk_radio_button_new_with_mnemonic (NULL, _("inactif"));
  gtk_widget_show (inactif);
  gtk_fixed_put (GTK_FIXED (fixed1), inactif, 440, 112);
  gtk_widget_set_size_request (inactif, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (inactif), inactif_group);
  inactif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (inactif));

  mail = gtk_label_new (_("Mail"));
  gtk_widget_show (mail);
  gtk_fixed_put (GTK_FIXED (fixed1), mail, 272, 152);
  gtk_widget_set_size_request (mail, 57, 17);

  ville = gtk_label_new (_("Ville"));
  gtk_widget_show (ville);
  gtk_fixed_put (GTK_FIXED (fixed1), ville, 272, 200);
  gtk_widget_set_size_request (ville, 57, 17);

  parking = gtk_label_new (_("parking \nassign\303\251"));
  gtk_widget_show (parking);
  gtk_fixed_put (GTK_FIXED (fixed1), parking, 272, 224);
  gtk_widget_set_size_request (parking, 80, 56);

  buttonajout = gtk_button_new ();
  gtk_widget_show (buttonajout);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajout, 496, 288);
  gtk_widget_set_size_request (buttonajout, 96, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonajout), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox15), label59, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  button_aff = gtk_button_new ();
  gtk_widget_show (button_aff);
  gtk_fixed_put (GTK_FIXED (fixed1), button_aff, 496, 352);
  gtk_widget_set_size_request (button_aff, 104, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_aff), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox20), label68, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label68), TRUE);

  label55 = gtk_label_new (_("*"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed1), label55, 456, 312);
  gtk_widget_set_size_request (label55, 189, 54);

  actif = gtk_radio_button_new_with_mnemonic (NULL, _("Actif"));
  gtk_widget_show (actif);
  gtk_fixed_put (GTK_FIXED (fixed1), actif, 368, 112);
  gtk_widget_set_size_request (actif, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (actif), actif_group);
  actif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (actif));

  staut = gtk_label_new (_("Statut"));
  gtk_widget_show (staut);
  gtk_fixed_put (GTK_FIXED (fixed1), staut, 272, 120);
  gtk_widget_set_size_request (staut, 57, 17);

  entry_role = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_role);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_role, 72, 240);
  gtk_widget_set_size_request (entry_role, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("Agent_de_nettoyage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("Agent_de_s\303\251curit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("Agent_d_accueil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("Agent_de_surveillance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("Responsable_Parking"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("Superviseur"));

  entry_ville = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_ville);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_ville, 360, 192);
  gtk_widget_set_size_request (entry_ville, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("La Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Menzah"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Sidi Bou Sa\303\257d"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _(" Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _(" Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Port-Kantaoui Kalaa Kebira "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Sidi Bou Ali"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Menzel_Chaker Gremda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Raoued"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Ksar_Hellal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Menzel Bourguiba Mateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Douar Hicher"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("El Intilaka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("La Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Nabeul Hammamet K\303\251libia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Gab\303\250d "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Mareth"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Sidi Bouzid Meknassy"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Chebba "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Boumerdes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Nefta"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Degache"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Sbe\303\257tla"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Thala"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _(" Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Bousalem"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Oued Meliz"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Medenine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville), _("Ben_Gardane "));

  entry_parking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_parking);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_parking, 360, 232);
  gtk_widget_set_size_request (entry_parking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_parking), _("parking1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_parking), _("parking2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_parking), _("parking3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_parking), _("parking4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_parking), _("parking5"));

  entry_region = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_region);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_region, 72, 200);
  gtk_widget_set_size_request (entry_region, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Mannouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Gab\303\250s "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Sidi Bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _(" Tozeur "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region), _("Kasserine Jendouba Medenine"));

  Ajout = gtk_label_new (_("Ajout"));
  gtk_widget_show (Ajout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Ajout);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  treeview_agents = gtk_tree_view_new ();
  gtk_widget_show (treeview_agents);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_agents, 0, 112);
  gtk_widget_set_size_request (treeview_agents, 729, 192);

  entry_cin_cher = gtk_entry_new ();
  gtk_widget_show (entry_cin_cher);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_cin_cher, 176, 64);
  gtk_widget_set_size_request (entry_cin_cher, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_cher), 8226);

  label25 = gtk_label_new_with_mnemonic (_("<span foreground=\"#1a3a6e\">****Bienvenue dans l'espace d'affichage des agents****</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 88, 16);
  gtk_widget_set_size_request (label25, 0, 17);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 0, 312);
  gtk_widget_set_size_request (button4, 74, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox4), label23, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 176, 312);
  gtk_widget_set_size_request (button6, 98, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label26 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox6), label26, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 80, 312);
  gtk_widget_set_size_request (button5, 98, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 272, 312);
  gtk_widget_set_size_request (button7, 106, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox7), label27, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label74 = gtk_label_new (_("label74"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed2), label74, 400, 96);
  gtk_widget_set_size_request (label74, 49, 17);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 520, 312);
  gtk_widget_set_size_request (button8, 98, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Exporter"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox8), label28, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  button_chercher_aff = gtk_button_new ();
  gtk_widget_show (button_chercher_aff);
  gtk_fixed_put (GTK_FIXED (fixed2), button_chercher_aff, 360, 64);
  gtk_widget_set_size_request (button_chercher_aff, 109, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_chercher_aff), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox3), label22, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label29 = gtk_label_new (_("<span foreground=\"#1a3a6e\">Afficher selon Cin</span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed2), label29, 40, 56);
  gtk_widget_set_size_request (label29, 120, 40);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  c = gtk_label_new (_("affichage"));
  gtk_widget_show (c);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), c);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  label30 = gtk_label_new (_("<span foreground=\"#1a3a6e\">****Bienvenue dans l'espace de suppression d'agent****</span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 112, 16);
  gtk_widget_set_size_request (label30, 0, 17);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  entry_cin_cher2 = gtk_entry_new ();
  gtk_widget_show (entry_cin_cher2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_cin_cher2, 176, 80);
  gtk_widget_set_size_request (entry_cin_cher2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_cher2), 8226);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed3), button11, 40, 256);
  gtk_widget_set_size_request (button11, 74, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox11), label34, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label31 = gtk_label_new (_("Entrer le cin \nd'agent a suuprimer"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed3), label31, 16, 72);
  gtk_widget_set_size_request (label31, 139, 47);

  button_cher2 = gtk_button_new ();
  gtk_widget_show (button_cher2);
  gtk_fixed_put (GTK_FIXED (fixed3), button_cher2, 368, 80);
  gtk_widget_set_size_request (button_cher2, 104, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_cher2), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox10), label33, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed3), button9, 368, 160);
  gtk_widget_set_size_request (button9, 112, 35);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox9), label32, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  rs = gtk_label_new (_("*"));
  gtk_widget_show (rs);
  gtk_fixed_put (GTK_FIXED (fixed3), rs, 288, 200);
  gtk_widget_set_size_request (rs, 256, 48);

  check = gtk_check_button_new ();
  gtk_widget_show (check);
  gtk_fixed_put (GTK_FIXED (fixed3), check, 368, 128);
  gtk_widget_set_size_request (check, 118, 24);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (check), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox21), label70, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label70), TRUE);

  supppression = gtk_label_new (_("supression"));
  gtk_widget_show (supppression);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), supppression);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry_cin1_modif = gtk_entry_new ();
  gtk_widget_show (entry_cin1_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_cin1_modif, 168, 64);
  gtk_widget_set_size_request (entry_cin1_modif, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin1_modif), 8226);

  label58 = gtk_label_new (_("<span foreground=\"#1a3a6e\">****Bienvenue dans l'espace de modificatin d'agent****</span>"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed4), label58, 104, 24);
  gtk_widget_set_size_request (label58, 0, 17);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  buttonchercher = gtk_button_new ();
  gtk_widget_show (buttonchercher);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonchercher, 352, 64);
  gtk_widget_set_size_request (buttonchercher, 112, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonchercher), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox16), label62, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label62), TRUE);

  cin1_modif = gtk_label_new (_(" <span foreground=\"#1a3a6e\">Entrer le CIN</span>"));
  gtk_widget_show (cin1_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), cin1_modif, 48, 56);
  gtk_widget_set_size_request (cin1_modif, 120, 45);
  gtk_label_set_use_markup (GTK_LABEL (cin1_modif), TRUE);

  buttonenregistrer = gtk_button_new ();
  gtk_widget_show (buttonenregistrer);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonenregistrer, 440, 376);
  gtk_widget_set_size_request (buttonenregistrer, 112, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonenregistrer), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox17), label61, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed5, 0, 104);
  gtk_widget_set_size_request (fixed5, 0, 0);

  entry__nom_modif = gtk_entry_new ();
  gtk_widget_show (entry__nom_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry__nom_modif, 72, 40);
  gtk_widget_set_size_request (entry__nom_modif, 176, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry__nom_modif), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry__nom_modif), 8226);

  entry_prenom_modif = gtk_entry_new ();
  gtk_widget_show (entry_prenom_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_prenom_modif, 360, 40);
  gtk_widget_set_size_request (entry_prenom_modif, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_modif), 8226);

  entry_telephone_modif = gtk_entry_new ();
  gtk_widget_show (entry_telephone_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_telephone_modif, 360, 72);
  gtk_widget_set_size_request (entry_telephone_modif, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_telephone_modif), 8226);

  jr_modif_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  jr_modif = gtk_spin_button_new (GTK_ADJUSTMENT (jr_modif_adj), 1, 0);
  gtk_widget_show (jr_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), jr_modif, 80, 120);
  gtk_widget_set_size_request (jr_modif, 48, 24);

  m_modif_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  m_modif = gtk_spin_button_new (GTK_ADJUSTMENT (m_modif_adj), 1, 0);
  gtk_widget_show (m_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), m_modif, 136, 120);
  gtk_widget_set_size_request (m_modif, 48, 24);

  an_modif_adj = gtk_adjustment_new (0, 1900, 2010, 1, 10, 10);
  an_modif = gtk_spin_button_new (GTK_ADJUSTMENT (an_modif_adj), 1, 0);
  gtk_widget_show (an_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), an_modif, 192, 120);
  gtk_widget_set_size_request (an_modif, 60, 27);

  jr1_modif_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  jr1_modif = gtk_spin_button_new (GTK_ADJUSTMENT (jr1_modif_adj), 1, 0);
  gtk_widget_show (jr1_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), jr1_modif, 80, 160);
  gtk_widget_set_size_request (jr1_modif, 48, 24);

  m1_modif_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  m1_modif = gtk_spin_button_new (GTK_ADJUSTMENT (m1_modif_adj), 1, 0);
  gtk_widget_show (m1_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), m1_modif, 136, 160);
  gtk_widget_set_size_request (m1_modif, 48, 24);

  an1_modif_adj = gtk_adjustment_new (0, 2024, 2050, 1, 10, 10);
  an1_modif = gtk_spin_button_new (GTK_ADJUSTMENT (an1_modif_adj), 1, 0);
  gtk_widget_show (an1_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), an1_modif, 192, 160);
  gtk_widget_set_size_request (an1_modif, 60, 27);

  entry_mail_modif = gtk_entry_new ();
  gtk_widget_show (entry_mail_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_mail_modif, 360, 144);
  gtk_widget_set_size_request (entry_mail_modif, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mail_modif), 8226);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed5), button13, 8, 272);
  gtk_widget_set_size_request (button13, 74, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button13), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox13), label42, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  entry_cin_modif = gtk_entry_new ();
  gtk_widget_show (entry_cin_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_cin_modif, 72, 80);
  gtk_widget_set_size_request (entry_cin_modif, 176, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry_cin_modif), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_modif), 8226);

  label49 = gtk_label_new (_("parking \nassign\303\251"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed5), label49, 272, 224);
  gtk_widget_set_size_request (label49, 80, 56);

  dn_modif = gtk_label_new (_("date de\nnaissance"));
  gtk_widget_show (dn_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), dn_modif, 8, 112);
  gtk_widget_set_size_request (dn_modif, 68, 38);

  db_modif = gtk_label_new (_("date d\303\251but\n d'emploi"));
  gtk_widget_show (db_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), db_modif, 0, 144);
  gtk_widget_set_size_request (db_modif, 73, 52);

  region_modif = gtk_label_new (_("R\303\251gion"));
  gtk_widget_show (region_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), region_modif, 8, 208);
  gtk_widget_set_size_request (region_modif, 57, 17);

  role_modif = gtk_label_new (_("Role"));
  gtk_widget_show (role_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), role_modif, 16, 248);
  gtk_widget_set_size_request (role_modif, 57, 17);

  entry_region_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_region_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_region_modif, 72, 200);
  gtk_widget_set_size_request (entry_region_modif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Mannouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Gab\303\250s "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Sidi Bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _(" Tozeur "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_region_modif), _("Kasserine Jendouba Medenine"));

  entry_role_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_role_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_role_modif, 72, 240);
  gtk_widget_set_size_request (entry_role_modif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role_modif), _("Agent de nettoyage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role_modif), _("Agent de s\303\251curit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role_modif), _("Agent d'accueil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role_modif), _("Agent de surveillance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role_modif), _(" Responsable Parking"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role_modif), _("Superviseur"));

  actif_modif = gtk_radio_button_new_with_mnemonic (NULL, _("Actif"));
  gtk_widget_show (actif_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), actif_modif, 368, 112);
  gtk_widget_set_size_request (actif_modif, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (actif_modif), actif_modif_group);
  actif_modif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (actif_modif));

  inactif_modif = gtk_radio_button_new_with_mnemonic (NULL, _("inactif"));
  gtk_widget_show (inactif_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), inactif_modif, 440, 112);
  gtk_widget_set_size_request (inactif_modif, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (inactif_modif), inactif_modif_group);
  inactif_modif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (inactif_modif));

  ville_modif = gtk_label_new (_("Ville"));
  gtk_widget_show (ville_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), ville_modif, 272, 200);
  gtk_widget_set_size_request (ville_modif, 57, 17);

  mail_modif = gtk_label_new (_("Mail"));
  gtk_widget_show (mail_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), mail_modif, 272, 152);
  gtk_widget_set_size_request (mail_modif, 57, 17);

  entry_ville_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_ville_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_ville_modif, 360, 192);
  gtk_widget_set_size_request (entry_ville_modif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("La Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("El Menzah"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Sidi Bou Sa\303\257d"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _(" Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _(" Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Port El Kantaoui Kalaa Kebira "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Sidi Bou Ali"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Menzel Chaker Gremda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Raoued"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Ksar Hellal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Menzel Bourguiba Mateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Douar Hicher"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("El Intilaka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("La Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Nabeul Hammamet K\303\251libia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Gab\303\250s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Mareth"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Sidi Bouzid Meknassy"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Chebba "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Boumerdes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Nefta"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Degache"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Sbe\303\257tla"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Thala"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _(" Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Bousalem"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Oued Meliz"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Medenine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_ville_modif), _("Ben Gardane "));

  entrty_parking_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entrty_parking_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entrty_parking_modif, 360, 232);
  gtk_widget_set_size_request (entrty_parking_modif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrty_parking_modif), _("parking1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrty_parking_modif), _("parking2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrty_parking_modif), _("parking3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrty_parking_modif), _("parking4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entrty_parking_modif), _("parking5"));

  nom_modif = gtk_label_new (_("Nom"));
  gtk_widget_show (nom_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), nom_modif, 16, 48);
  gtk_widget_set_size_request (nom_modif, 57, 17);

  cin_modif = gtk_label_new (_("cin"));
  gtk_widget_show (cin_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), cin_modif, 16, 88);
  gtk_widget_set_size_request (cin_modif, 57, 17);

  prenom_modif = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (prenom_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), prenom_modif, 272, 40);
  gtk_widget_set_size_request (prenom_modif, 57, 17);

  statut_modif = gtk_label_new (_("Statut"));
  gtk_widget_show (statut_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), statut_modif, 272, 120);
  gtk_widget_set_size_request (statut_modif, 57, 17);

  telephone_modif = gtk_label_new (_("num\303\251ro de\n telephone"));
  gtk_widget_show (telephone_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), telephone_modif, 272, 64);
  gtk_widget_set_size_request (telephone_modif, 80, 48);

  error_modif = gtk_label_new (_("*"));
  gtk_widget_show (error_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), error_modif, 352, 8);
  gtk_widget_set_size_request (error_modif, 140, 21);

  label73 = gtk_label_new (_("label73"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed4), label73, 480, 416);
  gtk_widget_set_size_request (label73, 49, 17);

  modification = gtk_label_new (_("modification"));
  gtk_widget_show (modification);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), modification);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  label64 = gtk_label_new (_("<span foreground=\"#1a3a6e\">****Bienvenue dans l'espace d'affichages Resrervations****</span>"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed6), label64, 104, 24);
  gtk_widget_set_size_request (label64, 0, 17);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  treeview_reservations = gtk_tree_view_new ();
  gtk_widget_show (treeview_reservations);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview_reservations, 168, 136);
  gtk_widget_set_size_request (treeview_reservations, 300, 200);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed6), button14, 424, 64);
  gtk_widget_set_size_request (button14, 103, 30);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button14), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox18), label65, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed6), button15, 32, 296);
  gtk_widget_set_size_request (button15, 74, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button15), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox19), label67, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  label71 = gtk_label_new (_("<span foreground=\"#1a3a6e\">Date Reservation</span>"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed6), label71, 80, 72);
  gtk_widget_set_size_request (label71, 136, 16);
  gtk_label_set_use_markup (GTK_LABEL (label71), TRUE);

  jr_res_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jr_res = gtk_spin_button_new (GTK_ADJUSTMENT (jr_res_adj), 1, 0);
  gtk_widget_show (jr_res);
  gtk_fixed_put (GTK_FIXED (fixed6), jr_res, 208, 64);
  gtk_widget_set_size_request (jr_res, 60, 27);

  m_res_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  m_res = gtk_spin_button_new (GTK_ADJUSTMENT (m_res_adj), 1, 0);
  gtk_widget_show (m_res);
  gtk_fixed_put (GTK_FIXED (fixed6), m_res, 272, 64);
  gtk_widget_set_size_request (m_res, 60, 27);

  an_res_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  an_res = gtk_spin_button_new (GTK_ADJUSTMENT (an_res_adj), 1, 0);
  gtk_widget_show (an_res);
  gtk_fixed_put (GTK_FIXED (fixed6), an_res, 336, 64);
  gtk_widget_set_size_request (an_res, 80, 27);

  label72 = gtk_label_new (_("label72"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed6), label72, 472, 104);
  gtk_widget_set_size_request (label72, 49, 17);

  button_aff_res = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button_aff_res);
  gtk_fixed_put (GTK_FIXED (fixed6), button_aff_res, 496, 160);
  gtk_widget_set_size_request (button_aff_res, 74, 29);

  label63 = gtk_label_new (_("Reservation"));
  gtk_widget_show (label63);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label63);

  g_signal_connect ((gpointer) buttonajout, "clicked",
                    G_CALLBACK (on_buttonajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff, "clicked",
                    G_CALLBACK (on_button_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_agents, "row_activated",
                    G_CALLBACK (on_treeview_agents_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_chercher_aff, "clicked",
                    G_CALLBACK (on_button_chercher_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cher2, "clicked",
                    G_CALLBACK (on_button_cher2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonchercher, "clicked",
                    G_CALLBACK (on_buttonchercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonenregistrer, "clicked",
                    G_CALLBACK (on_buttonenregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_reservations, "row_activated",
                    G_CALLBACK (on_treeview_reservation_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_aff_res, "clicked",
                    G_CALLBACK (on_button_aff_res_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (window1, entry_cin, "entry_cin");
  GLADE_HOOKUP_OBJECT (window1, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (window1, entry_telephone, "entry_telephone");
  GLADE_HOOKUP_OBJECT (window1, jr, "jr");
  GLADE_HOOKUP_OBJECT (window1, m, "m");
  GLADE_HOOKUP_OBJECT (window1, an, "an");
  GLADE_HOOKUP_OBJECT (window1, jr1, "jr1");
  GLADE_HOOKUP_OBJECT (window1, m1, "m1");
  GLADE_HOOKUP_OBJECT (window1, an1, "an1");
  GLADE_HOOKUP_OBJECT (window1, entry_mail, "entry_mail");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, nom, "nom");
  GLADE_HOOKUP_OBJECT (window1, cin, "cin");
  GLADE_HOOKUP_OBJECT (window1, dn, "dn");
  GLADE_HOOKUP_OBJECT (window1, db, "db");
  GLADE_HOOKUP_OBJECT (window1, region, "region");
  GLADE_HOOKUP_OBJECT (window1, role, "role");
  GLADE_HOOKUP_OBJECT (window1, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (window1, telephone, "telephone");
  GLADE_HOOKUP_OBJECT (window1, inactif, "inactif");
  GLADE_HOOKUP_OBJECT (window1, mail, "mail");
  GLADE_HOOKUP_OBJECT (window1, ville, "ville");
  GLADE_HOOKUP_OBJECT (window1, parking, "parking");
  GLADE_HOOKUP_OBJECT (window1, buttonajout, "buttonajout");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label59, "label59");
  GLADE_HOOKUP_OBJECT (window1, button_aff, "button_aff");
  GLADE_HOOKUP_OBJECT (window1, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window1, image20, "image20");
  GLADE_HOOKUP_OBJECT (window1, label68, "label68");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, actif, "actif");
  GLADE_HOOKUP_OBJECT (window1, staut, "staut");
  GLADE_HOOKUP_OBJECT (window1, entry_role, "entry_role");
  GLADE_HOOKUP_OBJECT (window1, entry_ville, "entry_ville");
  GLADE_HOOKUP_OBJECT (window1, entry_parking, "entry_parking");
  GLADE_HOOKUP_OBJECT (window1, entry_region, "entry_region");
  GLADE_HOOKUP_OBJECT (window1, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, treeview_agents, "treeview_agents");
  GLADE_HOOKUP_OBJECT (window1, entry_cin_cher, "entry_cin_cher");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, label74, "label74");
  GLADE_HOOKUP_OBJECT (window1, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, button_chercher_aff, "button_chercher_aff");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, c, "c");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, entry_cin_cher2, "entry_cin_cher2");
  GLADE_HOOKUP_OBJECT (window1, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image11, "image11");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, button_cher2, "button_cher2");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, rs, "rs");
  GLADE_HOOKUP_OBJECT (window1, check, "check");
  GLADE_HOOKUP_OBJECT (window1, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window1, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window1, image21, "image21");
  GLADE_HOOKUP_OBJECT (window1, label70, "label70");
  GLADE_HOOKUP_OBJECT (window1, supppression, "supppression");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, entry_cin1_modif, "entry_cin1_modif");
  GLADE_HOOKUP_OBJECT (window1, label58, "label58");
  GLADE_HOOKUP_OBJECT (window1, buttonchercher, "buttonchercher");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, label62, "label62");
  GLADE_HOOKUP_OBJECT (window1, cin1_modif, "cin1_modif");
  GLADE_HOOKUP_OBJECT (window1, buttonenregistrer, "buttonenregistrer");
  GLADE_HOOKUP_OBJECT (window1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label61, "label61");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, entry__nom_modif, "entry__nom_modif");
  GLADE_HOOKUP_OBJECT (window1, entry_prenom_modif, "entry_prenom_modif");
  GLADE_HOOKUP_OBJECT (window1, entry_telephone_modif, "entry_telephone_modif");
  GLADE_HOOKUP_OBJECT (window1, jr_modif, "jr_modif");
  GLADE_HOOKUP_OBJECT (window1, m_modif, "m_modif");
  GLADE_HOOKUP_OBJECT (window1, an_modif, "an_modif");
  GLADE_HOOKUP_OBJECT (window1, jr1_modif, "jr1_modif");
  GLADE_HOOKUP_OBJECT (window1, m1_modif, "m1_modif");
  GLADE_HOOKUP_OBJECT (window1, an1_modif, "an1_modif");
  GLADE_HOOKUP_OBJECT (window1, entry_mail_modif, "entry_mail_modif");
  GLADE_HOOKUP_OBJECT (window1, button13, "button13");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, entry_cin_modif, "entry_cin_modif");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, dn_modif, "dn_modif");
  GLADE_HOOKUP_OBJECT (window1, db_modif, "db_modif");
  GLADE_HOOKUP_OBJECT (window1, region_modif, "region_modif");
  GLADE_HOOKUP_OBJECT (window1, role_modif, "role_modif");
  GLADE_HOOKUP_OBJECT (window1, entry_region_modif, "entry_region_modif");
  GLADE_HOOKUP_OBJECT (window1, entry_role_modif, "entry_role_modif");
  GLADE_HOOKUP_OBJECT (window1, actif_modif, "actif_modif");
  GLADE_HOOKUP_OBJECT (window1, inactif_modif, "inactif_modif");
  GLADE_HOOKUP_OBJECT (window1, ville_modif, "ville_modif");
  GLADE_HOOKUP_OBJECT (window1, mail_modif, "mail_modif");
  GLADE_HOOKUP_OBJECT (window1, entry_ville_modif, "entry_ville_modif");
  GLADE_HOOKUP_OBJECT (window1, entrty_parking_modif, "entrty_parking_modif");
  GLADE_HOOKUP_OBJECT (window1, nom_modif, "nom_modif");
  GLADE_HOOKUP_OBJECT (window1, cin_modif, "cin_modif");
  GLADE_HOOKUP_OBJECT (window1, prenom_modif, "prenom_modif");
  GLADE_HOOKUP_OBJECT (window1, statut_modif, "statut_modif");
  GLADE_HOOKUP_OBJECT (window1, telephone_modif, "telephone_modif");
  GLADE_HOOKUP_OBJECT (window1, error_modif, "error_modif");
  GLADE_HOOKUP_OBJECT (window1, label73, "label73");
  GLADE_HOOKUP_OBJECT (window1, modification, "modification");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, label64, "label64");
  GLADE_HOOKUP_OBJECT (window1, treeview_reservations, "treeview_reservations");
  GLADE_HOOKUP_OBJECT (window1, button14, "button14");
  GLADE_HOOKUP_OBJECT (window1, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, label65, "label65");
  GLADE_HOOKUP_OBJECT (window1, button15, "button15");
  GLADE_HOOKUP_OBJECT (window1, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window1, image19, "image19");
  GLADE_HOOKUP_OBJECT (window1, label67, "label67");
  GLADE_HOOKUP_OBJECT (window1, label71, "label71");
  GLADE_HOOKUP_OBJECT (window1, jr_res, "jr_res");
  GLADE_HOOKUP_OBJECT (window1, m_res, "m_res");
  GLADE_HOOKUP_OBJECT (window1, an_res, "an_res");
  GLADE_HOOKUP_OBJECT (window1, label72, "label72");
  GLADE_HOOKUP_OBJECT (window1, button_aff_res, "button_aff_res");
  GLADE_HOOKUP_OBJECT (window1, label63, "label63");

  return window1;
}

