/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *p1;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label68;
  GtkWidget *p3;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label67;
  GtkWidget *p2;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Système de Parking"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);
  gtk_widget_set_size_request (fixed1, 737, 422);

  label1 = gtk_label_new (_("<span foreground=\"#1a3a6e\" size=\"x-large\"><b>Bienvenue dans votre système de parking</b></span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 100, 100);
  gtk_widget_set_size_request (label1, 550, 60);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  p1 = gtk_button_new ();
  gtk_widget_show (p1);
 gtk_fixed_put (GTK_FIXED (fixed1), p1, 120, 280);
 gtk_widget_set_size_request (p1, 150, 60);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (p1), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox13), label68, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label68), TRUE);

  p3 = gtk_button_new ();
  gtk_widget_show (p3);
  gtk_fixed_put (GTK_FIXED (fixed1), p3, 480, 280);
  gtk_widget_set_size_request (p3, 150, 60);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (p3), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Gestion de Parking "));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox12), label67, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  p2 = gtk_button_new_with_mnemonic (_("Gestion des Agents"));
  gtk_widget_show (p2);
  gtk_fixed_put (GTK_FIXED (fixed1), p2, 300, 280);
  gtk_widget_set_size_request (p2, 150, 60);

  g_signal_connect ((gpointer) p1, "clicked",
                    G_CALLBACK (on_inscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) p3, "clicked",
                    G_CALLBACK (on_loginbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) p2, "clicked",
                    G_CALLBACK (on_p2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, p1, "p1");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label68, "label68");
  GLADE_HOOKUP_OBJECT (window1, p3, "p3");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label67, "label67");
  GLADE_HOOKUP_OBJECT (window1, p2, "p2");

  return window1;
}

